### ISSUE TITLE
Squoosh doesn’t work with 

### ISSUE THREAD

**Issue by danhalliday** [stevecheckoway/squoosh#1]
Squoosh ignores files with the following `doctype`:

    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

It is noted in the docs that Squoosh ignores files not starting with `<!doctype html>`, but is this case intended?

**Comment by stevecheckoway** [comment]
Yes, that’s intentional. It only supports HTML. XHTML must be valid XML which has very different (and much more strict) rules.

I’m intentionally not supporting HTML 4 either (which has different rules too).
